### ISSUE TITLE
Refaire toute la partie backend en PHP avec Drupal

### ISSUE THREAD

**Issue by ghoullier** [glebreton/lapetiterennes#1]

**Comment by modye** [comment]
Bonjour,

Je pense personnellement qu'une intégration digitale en JSF serait judicieuse.

Cordialement

**Comment by glebreton** [comment]
J'attend la pull request !

**Comment by ghoullier** [comment]
L'utilisation d'un outil comme http://javatophp.com/demo.html peut-elle être pertinente?

**Comment by glebreton** [comment]
Bordel ! C'est quoi cette merde ??!
